version: '3.5'

services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'node-cache:/root/.npm'
      - 'node-cache:/usr/src/app/node_modules'
      - 'bs-cache:/usr/local/lib'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

volumes:
  node-cache:
  bs-cache: