version: '3.5'

services:

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - 'web-volume:/usr/src/app'
      - '/usr/local/lib'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development

volumes:
  web-volume: