version: '3.5'

services:

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/src:/usr/src/app/src
    ports:
      - '3000:3000'
      - '35729:35729'
    env_file:
      - .web.env