version: '3.5'

services:

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/usr/src/app
      - web_node_modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'
      - '35729:35729'
    env_file:
      - .web.env

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/usr/src/app
      - server_node_modules:/usr/src/app/node_modules
    ports:
      - '5000:5000'
    
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./db/.db.env

volumes:
  server_node_modules:
  web_node_modules:
  db: