version: '3.5'

services:

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
#       - 'node-cache:/root/.npm'
#       - 'bs-cache:/usr/local/lib'
      - ${PWD}/web:/usr/src/app
    ports:
      - '3000:3000'
      - '35729:35729'
    env_file:
      - .web.env

volumes:
  node-cache:
  bs-cache:
