version: '3.5'

services:

  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/src:/usr/src/app/src
      - web_node_modules:/usr/src/app/node_modules
    ports:
      - '3000:3000'
      - '35729:35729'
    env_file:
      - .web.env

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server/src:/usr/src/app/src
      - server_node_modules:/usr/src/app/node_modules
    ports:
      - '5000:5000'

volumes:
  server_node_modules:
  web_node_modules: